config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources :categories, :only => [:show]
  resources :cuisines, :only => [:show]
  resources :welcome, :only => [:index]
  resources :users, :only => [:create]

  resources :chefs, :only => [:new, :create, :show] do
    resources :recipes, :only => [:show]
  end
  resources :recipes, :only => [:new, :create, :show]
  resources :ingredients, :only => :show do
    resources :recipes, :only => :index
    member do
      post :recommend
    end
  end

end

app/models/categorisation.rb
class Categorisation < ActiveRecord::Base
  belongs_to :taxon, :polymorphic => true
  belongs_to :recipe
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :categorisations
  has_many :recipes, :through => :categorisations
end

app/models/chef.rb
class Chef < ActiveRecord::Base
  has_many :recipes

  accepts_nested_attributes_for :recipes
end

app/models/cuisine.rb
class Cuisine < ActiveRecord::Base
  has_many :categorisations
  has_many :recipes, :through => :categorisations
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  has_many :recipe_ingredients
  has_many :recipes, :through => :recipe_ingredients
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  belongs_to :chef
  has_many :categorisations

  has_many :categories, :through => :categorisations, :source => :taxon, :source_type => "Category"
  has_many :cuisines, :through => :categorisations, :source => :taxon, :source_type => "Cuisine"
  has_many :recipe_ingredients
  has_many :ingredients, :through => :recipe_ingredients

  accepts_nested_attributes_for :recipe_ingredients
  validates :title, :presence => true
end

app/models/recipe_ingredient.rb
class RecipeIngredient < ActiveRecord::Base
  belongs_to :recipe
  belongs_to :ingredient

  accepts_nested_attributes_for :ingredient
end

app/models/user.rb
class User < ActiveRecord::Base
  after_create do
    NotificationsMailer.welcome(self).deliver_now
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter do
    @categories = Category.all
    @cuisines = Cuisine.all
    # @user = User.new
    @ingredients = Ingredient.all
    # @recipes = Recipe.all
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @category = Category.find(params[:id])
  end
end

app/controllers/chefs_controller.rb
class ChefsController < ApplicationController
  def new
    @chef = Chef.new
    @recipe = Recipe.new
    @chef.recipes << @recipe
  end

  def create
    # binding.pry
    @chef = Chef.create!(allowed_params)
    # @chef.recipes << Recipe.create!(allowed_params[:recipe])
    redirect_to chef_path(@chef.id)
  end

  def show
    @chef = Chef.find(params[:id])
  end

  private
  def allowed_params
    params.require(:chef).permit(:name, :recipes_attributes => [:title])
  end
end

app/controllers/cuisines_controller.rb
class CuisinesController < ApplicationController
  def show
    @cuisine = Cuisine.find(params[:id])
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def show
    @recipe = Recipe.find(params[:id])
    @email = params[:email]
  end

  def recommend
    @recipe = Recipe.find(params[:id])
    @email = params[:email]
    NotificationsMailer.recommend(@email,@recipe).deliver_now
    redirect_to recipe_path(@recipe)
  end

  def new
    @recipe = Recipe.new
    # @recipe.recipe_ingredients << RecipeIngredient.new
    @recipe.ingredients << Ingredient.new
  end

  def create
    @recipe = Recipe.new(allowed_params)
    if @recipe.save
      redirect_to recipe_path(@recipe), :notice => "Recipe Created"
    else
      render :new
    end
  end

  # def show
  #   @recipe = Recipe.find(params[:id])
  # end

  def index
    @ingredient = Ingredient.find(params[:ingredient_id])
    @recipes = @ingredient.recipes
  end

  private
  def allowed_params
    params.require(:recipe).permit(:title)
  end
  def allowed_params_ingr
    params.require(:ingredient).permit(:name)
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def create
    @user = User.create!(allowed_params)
    flash[:notice] = "Added to Mailing List"
    # welcome(@user)
    redirect_to welcome_index_path
  end

  private
  def allowed_params
    params.require(:user).permit(:name, :email)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def create
    # binding.pry
    @user = User.create!(allowed_params)
    # binding.pry
    flash[:notice] = "Added to Mailing List"
    redirect_to welcome_index_path
  end

  private
  def allowed_params
    params.require(:user).permit(:name, :email)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @user = User.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/chefs_helper.rb
module ChefsHelper
end

app/helpers/cuisines_helper.rb
module CuisinesHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/categories/_category.html.haml
%li.category
  = link_to category.name, category_path(category)

app/views/categories/show.html.haml
%h1 My Amazing Category #{@category.name}

%h3 Recipes

%ul
  = render @category.recipes

app/views/chefs/new.html.haml
= form_for @chef do |f|
  %fieldset
    = f.label :name
    = f.text_field :name
  %fieldset
    = f.fields_for :recipes do |r|
      = r.label :title
      = r.text_field :title
  %fieldset
    = f.submit

app/views/chefs/show.html.haml
= @chef.name

%h4
  - @chef.recipes.each do |r|
    = link_to r.title, chef_recipe_path(@chef,r)

app/views/cuisines/_cuisine.html.haml
%li.cuisine
  = link_to cuisine.name, cuisine_path(cuisine)

app/views/cuisines/show.html.haml
%h1 My Amazing #{@cuisine.name} Cuisine

%h3 Recipes

%ul
  = render @cuisine.recipes

app/views/recipes/_recipe.html.haml
%li.recipe
  %h4=recipe.title

app/views/recipes/index.html.haml
%h2
  All #{@ingredient.name} Recipes

= render @recipes

app/views/recipes/new.html.haml
= render :partial => 'shared/errors', :locals => {:model=> @recipe}

= form_for @recipe do |f|
  %fieldset
    = f.label :title
    = f.text_field :title


  = f.fields_for :recipe_ingredient do |i|
    = i.fields_for :ingredient do |k|
      %fieldset
        = k.label :ingredient
        = k.text_field :ingredient

  %fieldset
    = f.submit "Save"

app/views/recipes/show.html.haml
%h2= @recipe.title

= form_tag(recommend_recipe_path, :method => "post") do
  = label_tag(:email)
  = text_field_tag(:email)
  = submit_tag("Recommend to a friend")